# Generated by Django 4.2.8 on 2024-06-11 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=250)),
                ("companyurl", models.URLField(blank=True, verbose_name="Company URL")),
                ("location", models.CharField(blank=True, max_length=250)),
                ("title", models.CharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
                ("job_start_date", models.DateField(blank=True, null=True)),
                ("job_end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="path to company image, local or otherwise",
                        max_length=250,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "04. Jobs",
                "db_table": "jobs",
                "ordering": ["-job_end_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                (
                    "suffix",
                    models.CharField(blank=True, help_text="e.g. PhD", max_length=255),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True, help_text="e.g. city such as Boston", max_length=255
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="e.g. MA or Italy", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="e.g. Developer", max_length=255
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("site", models.URLField(blank=True)),
                ("twittername", models.CharField(blank=True, max_length=100)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillAndSkillLevel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Expert", "Expert"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "07. Skills",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=250)),
                ("authors", models.TextField()),
                ("journal", models.CharField(max_length=150)),
                ("year", models.IntegerField(default=2024)),
                ("link", models.URLField(blank=True, verbose_name="Publication URL")),
                (
                    "personal_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "14. Publications",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.TextField(
                        blank=True, help_text="Text shown in project list"
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        help_text="Text shown in modals appearing when clicking on images",
                    ),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "personal_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "12. Projects",
            },
        ),
        migrations.CreateModel(
            name="ProgrammingArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "programming_area_name",
                    models.CharField(
                        choices=[("FRONTEND", "Frontend"), ("BACKEND", "Backend")],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "programming_language_name",
                    models.CharField(max_length=25, null=True),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_area",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "08. Programming areas",
                "ordering": ["programming_area_name"],
            },
        ),
        migrations.CreateModel(
            name="Overview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "personal_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "02. Overview",
            },
        ),
        migrations.CreateModel(
            name="JobAccomplishment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_accomplishment", models.TextField()),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accomplishment",
                        to="resume.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "05. Job Accomplishments",
                "db_table": "jobaccomplishment",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="personal_info_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="resume.personalinfo",
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("location", models.CharField(blank=True, max_length=250)),
                ("schoolurl", models.URLField(blank=True, verbose_name="School URL")),
                ("education_start_date", models.DateField(blank=True, null=True)),
                ("education_end_date", models.DateField(blank=True, null=True)),
                ("degree", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "personal_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="resume.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "03. Education",
                "ordering": ["-education_end_date", "id"],
            },
        ),
    ]
